<?php

namespace AppBundle\Repository;

/**
 * FrsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FrsRepository extends \Doctrine\ORM\EntityRepository
{
}
