<?php

namespace AppBundle\Repository;
use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository implements UserLoaderInterface
{
 /**
     * Loads the user for the given username.
     *
     * This method must return null if the user is not found
     *
     * @param string $username The username
     *
     * @return UserInterface|null
     */
	    public function loadUserByUsername($username)
    {
        return $this->createQuery('u')
         ->where('username = :username OR email = :email')
         ->setParameter('username', $username)
         ->setParameter('email', $username)
         ->getQuery()
         ->getOneOrNullResult();
    }
    public function findSomethingByUser(User $user)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT t FROM AppBundle:User u '.
                'WHERE u.username > :username'
        )->setParameter('username', $user->getUsername());

        return $query->getResult();
    }
}
